[graph]
all-features = true

[advisories]
version = 2
ignore = [
]

[licenses]
version = 2
allow = [
	"Apache-2.0",
	"MIT",
	"MIT-0",
	"Unicode-3.0",
]

[bans]
multiple-versions = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# please don't make this list any longer qwq
allow-git = [
]
